[package]
name = "nvfanservice"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
cursive = "0.21.1"
cursive_core = "0.4.6"
nvml-wrapper = { git = "https://github.com/raum-dellamorte/nvml-wrapper.git" }
regex = "1.10.5"
sudo = "0.6.0"
